version: '3.8'
services:
  api:
    build: ..
    container_name: llmops-api
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=supersecretkey
    volumes:
      - ../data:/app/data
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: llmops-prometheus
    volumes:
      - ../docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: llmops-grafana
    ports:
      - "3000:3000"
    volumes:
      - ../grafana:/var/lib/grafana"
